
services:

  vertx-mongo-persistor:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/mod-mongo-persistor:4.0-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=io.vertx~mod-mongo-persistor
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json
    depends_on:
      - mongo
      - zookeeper1
      - zookeeper2
      - zookeeper3

  vertx-image-resizer:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/mod-image-resizer:3.1-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=fr.wseduc~mod-image-resizer
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json
    depends_on:
      - localstack

  vertx-zip:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/mod-zip:3.1-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=fr.wseduc~mod-zip
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-postgresql:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/mod-postgresql:2.0-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=fr.wseduc~mod-postgresql
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json
    depends_on:
      - postgres

  vertx-json-schema-validator:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/mod-json-schema-validator:2.0-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=com.opendigitaleducation~mod-json-schema-validator
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-pdf-generator:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/mod-pdf-generator:2.0-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=fr.wseduc~mod-pdf-generator
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-infra:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/infra:6.6-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=org.entcore~infra
    volumes:
      - ./assets:/srv/springboard/assets
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json
    depends_on:
      - neo4j
      - postgres
      - mongo
      - redis
      - zookeeper1
      - zookeeper2
      - zookeeper3

  vertx-app-registry:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/app-registry:6.6-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=org.entcore~app-registry
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-session:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/session-redis:2.0-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=com.opendigitaleducation~session-redis
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-auth:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/auth:6.6-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=org.entcore~auth
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-directory:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/directory:6.6-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=org.entcore~directory
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-workspace:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/workspace:6.6-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=org.entcore~workspace
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-communication:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/communication:6.6-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=org.entcore~communication
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-portal:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/springboard-portal:6.6-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=org.entcore~portal
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-conversation:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/conversation:6.6-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=org.entcore~conversation
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-feeder:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/feeder:6.6-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=org.entcore~feeder
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./aaf-duplicates-test:/home/wse/aaf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-timeline:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/timeline:6.6-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=org.entcore~timeline
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-cas:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/cas:6.6-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=org.entcore~cas
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-archive:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/archive:6.6-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=org.entcore~archive
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-admin:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/admin:6.6-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=org.entcore~admin
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-actualites:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/actualites:2.0-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=net.atos~actualites
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  vertx-forum:
    image: maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/forum:2.0-zookeeper-SNAPSHOT
    user: "$DEFAULT_DOCKER_USER"
    environment:
      - MODE=cluster
      - ENABLED_SERVICES=net.atos~forum
    volumes:
      - ./ent-core.json:/srv/springboard/conf/vertx.conf
      - ./cluster-config/zookeeper.json:/srv/springboard/conf/zookeeper.json

  pdf:
    image: opendigitaleducation/node-pdf-generator:1.0.0
    ports:
      - "3000:3000"

  content-transformer:
    user: "$DEFAULT_DOCKER_USER"
    image: ghcr.io/edificeio/edifice-tiptap-transformer:1.0.2
    ports:
      - "3100:3000"

  neo4j:
    image: neo4j:3.1
    volumes:
      - ./neo4j-conf:/conf

  redis:
    image: redis:8

  elasticsearch:
    image: opensearchproject/opensearch:2.8.0
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      MEM_LIMIT: 1073741824
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
      - "9300:9300"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: We_1234
      POSTGRES_USER: web-education
      POSTGRES_DB: ong
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth-host=md5
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:7.0

  zookeeper1:
    image: zookeeper:3.9
    hostname: zookeeper1
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181

  zookeeper2:
    image: zookeeper:3.9
    hostname: zookeeper2
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181

  zookeeper3:
    image: zookeeper:3.9
    hostname: zookeeper3
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181

  traefik:
    image: traefik:3.4
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.zookeeper=true"
      - "--providers.zookeeper.endpoints=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      - "--providers.zookeeper.rootkey=ent-core/traefik"
      - "--entrypoints.web.address=:8090"
      - "--log.level=DEBUG"
    ports:
      - "8090:8090"
      - "8080:8080"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./cluster-config/init-s3:/etc/localstack/init

#   gradle:
#     image: opendigitaleducation/gradle:4.5.1
#     user: "$DEFAULT_DOCKER_USER"
#     working_dir: /home/gradle/project
#     volumes:
#       - ./:/home/gradle/project
#       - ~/.m2:/home/gradle/.m2
#       - ~/.gradle:/home/gradle/.gradle

#   node:
#     image: opendigitaleducation/node:18-alpine-pnpm
#     user: "$DEFAULT_DOCKER_USER"
#     working_dir: /home/node/app
#     volumes:
#       - ./:/home/node/app
#       - ~/.npm:/.npm
#       - .config:/.config

#   k6:
#     image: grafana/k6:master
#     user: "$DEFAULT_DOCKER_USER"
#     volumes:
#       - ./it/src:/home/k6/src
#       - ./it/resources:/home/k6/data
#     environment:
#       ROOT_URL: http://vertx:8090
#       DATA_ROOT_PATH: /home/k6/data
#       ADMC_LOGIN: tom.mate
#       ADMC_PASSWORD: password

#   k6-stress:
#     image: grafana/k6:master
#     user: "$DEFAULT_DOCKER_USER"
#     volumes:
#       - ./stress/src:/home/k6/src
#       - ./stress/resources:/home/k6/data
#     environment:
#       ROOT_URL: http://vertx:8090
#       DATA_ROOT_PATH: /home/k6/data
#       ADMC_LOGIN: tom.mate
#       ADMC_PASSWORD: password
#

