
mode=dev
ssl=false
host=http://localhost:8090
feeder=AAF
importDirectory=/home/wse/aaf
logDirectory=/tmp/log
httpProxy=true
applycommunication=true
webdavCredential=false
webdavHost=localhost
webdavUsername=
webdavPassword=
webdavInsecure=
exporter=ELIOT
exportPath=/tmp
exportDestination=
senderEmail=no-reply@ent.picardie.fr
neo4jAAFPlugin=false
neo4jUri=http://neo4j:7474
logoutCallback=
dbName=one_gridfs
mongoHost=mongo
mongoPort=27017
sqlDb=
sqlIp=
sqlUrl=jdbc:postgresql://postgres:5432/ong?stringtype=unspecified
sqlUsername=web-education
sqlPassword=We_1234
fsStoragePath=/srv/storage/
patternDefaultRegisteredService="^(http|https):\\/\\/.*"
patternUidRegisteredService=
patternUniversalisRegisteredService=
patternLeSiteTvRegisteredService=
patternKneRegisteredService=
patternPronoteRegisteredService=
patternEliotRegisteredService=
patternWebclasseursRegisteredService=
patternEducagriRegisteredService="^(http|https):\\/\\/www\\\\.educagrinet\\\\.educagri\\\\.fr\\/.*"
patternEduMediaRegisteredService="^(http|https):\\/\\/www\\\\.edumedia-sciences\\\\.com\\/.*"
patternGepiRegisteredService="^(http|https).*gepi.*"
patternMSELRegisteredService="^(http|https).*monstageenligne.*"
eliotExportedDelay=600000
eliotAppliCode=
eliotUri=
eliotSaasUri=
themes={"_id": "default","displayName": "default","path": "/assets/themes/leo/default/"},{"_id": "dyslexic","displayName": "dyslexic","path": "/assets/themes/leo/dyslexic/"}
resourcesApplications="workspace", "blog", "actualites", "wiki", "pages", "poll", "timelinegenerator", "rack", "forum", "community", "mindmap", "collaborativewall"
widgets={"name": "recorder", "path": "/public/template/record-me.html", "js": "/public/js/record-me.js"}, {"name": "calendar","path": "/public/template/calendar.html","js": "/public/js/calendar.js"},{"name": "notes","path": "/public/template/notes.html","js": "/public/js/notes.js"},{"name": "actualites","path": "/actualites/public/template/last-infos-widget.html","js": "/actualites/public/js/last-infos-widget.js","i18n": "/actualites/i18n"},{"name": "rss","path": "/rss/public/template/rss-widget.html","js": "/rss/public/js/rss-widget.js","i18n": "/rss/i18n"},{"name": "maxicours", "path": "/maxicours/public/template/maxicours-widget.html", "js": "/maxicours/public/js/maxicours-widget.js", "i18n": "/maxicours/i18n"},{"name": "cursus", "path": "/cursus/public/template/cursus-widget.html", "js": "/cursus/public/js/cursus-widget.js", "i18n": "/cursus/i18n"}
defaultCommunicationRules={"Structure-Personnel" : { "users" : "BOTH", "communiqueWith" : ["Structure-Teacher", "Structure-Relative", "Structure-Student"]},"Structure-Teacher" : { "users" : "BOTH", "communiqueWith" : ["Structure-Personnel", "Structure-Relative", "Structure-Student"]},"Structure-Student" : {"users" : "BOTH"},"Structure-Relative" : {"users" : "OUTGOING"},"Class-Personnel" : {"users" : "OUTGOING"},"Class-Teacher" : {"users" : "OUTGOING"},"Class-Student" : { "users" : "BOTH", "communiqueWith" : ["Class-Teacher", "Structure-Personnel"]},"Class-Relative" : { "users" : "BOTH", "Relative-Student" : "BOTH", "communiqueWith" : ["Structure-Personnel", "Class-Teacher"]}}
assetsPath=/srv/springboard
entcoreVersion=3.6.0
swiftUri=
swiftContainer=
swiftUser=
swiftKey=
passwordRegex=.*
cursusEndpoint=
cursusAuthConf={}
neo4jPlugin=false
activateEscalation=false
activationAutoLogin=false
skins={"localhost:8090":"openent" , "192.168.99.100:8090":"openent"}
sharedConf={"smsProvider": "OVH"}
smsProvider="Sinch"
authMandatoryFields={}
patternProEPSRegisteredService=
signKey=
samlMetadataFolder=
samlPrivateKey=
federationLoginUri=
federationCallBackParam=
samlServicesProviders={}
autoExport=false
smsProviders={"OVH": { "applicationKey": "", "applicationSecret": "", "consumerKey": "" }}
federatedAddress={}
activationWelcomeMessage=false
teacherForgotPasswordEmail=false
createdUserEmail=false
cnsConfig=[{}]
classDefaultRoles=false
keyring=true
themeVersion=0.20.0
patternGRRRegisteredService=
samlIssuer=
samlSLO=true
emailConfig=
skin=raw
modSftp=false
directoryCalendarSwitch=
moodleServer=
moodleWsPath=
timeSecondSynchCron=
numberOfMaxDuplicationTentatives=1
numberOfMaxPendingDuplication=1
timeDuplicationBeforeDelete=
idStudent=1
idEditingTeacher=1
idAuditeur=1
wstoken=
header=
deleteCategoryId=0
idGuest=1
publicBankCategoryId=1
mainCategoryId=1
userMail=
maxicoursWsEndpoint=
maxicoursConnectorEndpoint=
csrfToken=false
timeCheckNotifs=
fsAvatarPath=
flatAvatarStorage=false
adminZimbra=
garDemo=false
garExportPath=
garExportCron=
garIdENT=
garRessourcesHost=
garRessourcesCert=
garRessourcesKey=
garSftpHost=
garSftpPort=22
garSftpUsername=
garSftpPassphrase=
garSftpSshkey=
garSftpDirDest=
garSftpKnownHost=
academyPrefix=
mediacentrePaginationLimit=1
xsdRecipientList=[]
elasticServerURI=
elasticIndexName=
webConferenceBBBHost=
webConferenceBBBAPIEndpoint=
webConferenceBBBSecret=
webConferenceDefaultShare=[]
allowPublicLink=false
publicHolidays=
schoolHolidays=
zimbraMaxRecipients=50
rgpdCron= 
maxResponsesExportPDF=100
maxUsersSharing=1000
enableRbs=false
elasticSearchSsl=""
elasticSearchUsername=
elasticSearchPassword=
calendarSyncTTL=3600
wikiPaginationLimit=5
nextcloudQuota=
moodleDefaultShare=[]
notifyCron=
explorerEsUrl=http://elasticsearch:9200
sqlDb=ong
sqlIp=postgres
pgAdminUser=web-education
pgAdminPwd=We_1234
enableZimbra=false
minetestServer=
minetestDownload=
minetestPythonServerPort=
minetestPortRange=
minetestLink=
minetestWiki=
minetestMessaging=
minetestShuttingDownCron=
mediacentreUpdateFrequency=60000
magnetoUpdateFrequency=10000
magnetoIsStandalone=false
magnetoWebsocketMaxUsers=5000
magnetoWebsocketMaxUsersPerBoard=500
magnetoWebsocketPort=9092
supportThresholdDirectExportTickets=10000
loolServer=
loolTypeProvider=
loolUrlProvider=
garDevMode=true
mediacentreHighlightsPins=false
elasticServerURIs="[]"
notifyBoardTemplate=
mediacentreTextHighlightsPins=
enableCalendarReminder=false
calendarReminderCron=0 0 0 1 * ? 2099
themePlatform=
selfEnrollmentCategoryId=0
closingCron=
minHoursBeforeCancellation=24
daysBeforeNotifClosing=1
